# build release file for the lua project

name: release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: leafo/gh-actions-lua@v9
    - uses: leafo/gh-actions-luarocks@v4

    - name: Install dependencies
      run: luarocks install --only-deps ricer-dev-1.rockspec

    - name: Build binary
      run: luastatic main.lua $(whereis lua | cut -d ' ' -f 2 | sed 's/bin\/lua//')/lib/liblua.a -I$(whereis lua | cut -d ' ' -f 2 | sed 's/bin\/lua//')/include -o ricer

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ricer
        path: ricer
